# Deliberately permissive licenses accepted for statically linked production
# dependencies. Additions require an explicit policy review in this file.
threshold: 0.80
allow:
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - ImageMagick
  - MIT
  - MPL-2.0
