apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ .Release.Name }}-workload-authorizer
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups: ["scheduling.tenstorrent.com"]
      apiVersions: ["v1", "v1alpha1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["tenstorrentworkloads"]
  validations:
  - expression: authorizer.group('').resource('pods').namespace(request.namespace).check('create').allowed()
    message: creating a TenstorrentWorkload requires permission to create Pods in its namespace
    reason: Forbidden
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ .Release.Name }}-workload-authorizer
spec:
  policyName: {{ .Release.Name }}-workload-authorizer
  validationActions: [Deny, Audit]
