apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-node
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-node
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceslices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["topology.tenstorrent.com"]
  resources: ["tenstorrentnodetopologies"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-node
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-node
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaims"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["topology.tenstorrent.com"]
  resources: ["tenstorrentnodetopologies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["topology.tenstorrent.com"]
  resources: ["tenstorrentfabrictopologies"]
  verbs: ["get", "create"]
- apiGroups: ["topology.tenstorrent.com"]
  resources: ["tenstorrentfabrictopologies/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["scheduling.tenstorrent.com"]
  resources: ["tenstorrentworkloads"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["scheduling.tenstorrent.com"]
  resources: ["tenstorrentworkloads/status"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-controller
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-controller-lease
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  resourceNames: [{{ .Release.Name }}-controller]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-controller-lease
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-controller-lease
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
