apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: tenstorrent-wormhole-n150
  labels:
    app.kubernetes.io/name: tt-dra-driver
    app.kubernetes.io/component: dra-device-class
    tenstorrent.com/chip-series: wormhole
    tenstorrent.com/card-series: n150
spec:
  selectors:
  - cel:
      expression: |-
        device.driver == "tenstorrent.com/dra" &&
        device.attributes["tenstorrent.com"].chipSeries == "wormhole" &&
        device.attributes["tenstorrent.com"].cardSeries == "n150"
---
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: tenstorrent-wormhole-n300
  labels:
    app.kubernetes.io/name: tt-dra-driver
    app.kubernetes.io/component: dra-device-class
    tenstorrent.com/chip-series: wormhole
    tenstorrent.com/card-series: n300
spec:
  selectors:
  - cel:
      expression: |-
        device.driver == "tenstorrent.com/dra" &&
        device.attributes["tenstorrent.com"].chipSeries == "wormhole" &&
        device.attributes["tenstorrent.com"].cardSeries == "n300"
---
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: tenstorrent-blackhole-p100
  labels:
    app.kubernetes.io/name: tt-dra-driver
    app.kubernetes.io/component: dra-device-class
    tenstorrent.com/chip-series: blackhole
    tenstorrent.com/card-series: p100
spec:
  selectors:
  - cel:
      expression: |-
        device.driver == "tenstorrent.com/dra" &&
        device.attributes["tenstorrent.com"].chipSeries == "blackhole" &&
        device.attributes["tenstorrent.com"].cardSeries == "p100"
---
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: tenstorrent-blackhole-p150
  labels:
    app.kubernetes.io/name: tt-dra-driver
    app.kubernetes.io/component: dra-device-class
    tenstorrent.com/chip-series: blackhole
    tenstorrent.com/card-series: p150
spec:
  selectors:
  - cel:
      expression: |-
        device.driver == "tenstorrent.com/dra" &&
        device.attributes["tenstorrent.com"].chipSeries == "blackhole" &&
        device.attributes["tenstorrent.com"].cardSeries == "p150"
