apiVersion: v2
name: tenstorrent-dra
description: Tenstorrent Kubernetes DRA driver and topology controller
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.34.0-0"
home: https://github.com/varrahan/tenstorrent-dra-framework
sources:
  - https://github.com/varrahan/tenstorrent-dra-framework
